---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-services-disasterproject-com-v1alpha1-openldap
  failurePolicy: Fail
  name: vopenldap.kb.io
  rules:
  - apiGroups:
    - services.disasterproject.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openldaps
  sideEffects: None
