apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
  name: {{ include "openldap.fullname" . }}-controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openldap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "openldap.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      initContainers:
      - name: update-webhook
        image: docker.io/aescanero/micropki:0.1
        command: ['/micropki']
        args:
        - update
        - -caname
        - "{{ include "openldap.fullname" . }}-ca"
        - -certname
        - "{{ include "openldap.fullname" . }}-webhook-secret"
        - -fqdns
        - "{{ include "openldap.serviceAccountName" . }}.{{.Release.Namespace}}.svc"
        - -webhook
        - {{ include "openldap.fullname" . }}-webhook-service
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
        name: kube-rbac-proxy
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- if .Values.webhook.enabled }}
          - name: WEBHOOK_SECRET
            value: {{ include "openldap.fullname" . }}-webhook-secret
          {{- end }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        image: docker.io/aescanero/openldap-controller:0.1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
        {{- if .Values.securityContext }}
          {{- toYaml .Values.resources | nindent 12 }}
        {{- else }}
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        {{- end }}
        securityContext:
        {{- if .Values.securityContext }}
          {{- toYaml .Values.securityContext | nindent 8 }}
        {{- else }}
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        {{- end }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openldap.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "openldap.fullname" . }}-webhook-secret

          

