{{- if .Values.webhook.certManagerCert }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: {{ include "openldap.fullname" . }}
    app.kubernetes.io/instance: selfsigned-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: issuer
    app.kubernetes.io/part-of: {{ include "openldap.fullname" . }}
  name: {{ include "openldap.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
{{- end }}