---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
  name: {{ include "openldap.fullname" . }}-ca
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: ""
  tls.key: ""
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
  name: {{ include "openldap.fullname" . }}-webhook-secret
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: ""
  tls.key: ""
---