{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
  name: {{ include "openldap.fullname" . }}-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
{{- end -}}